---
title: "615 final project"
author: "Ying Li"
date: "2017Äê11ÔÂ30ÈÕ"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# twitter set up

```{r}
library(devtools)
library(twitteR)
library(streamR)
library(ROAuth)
library(reshape)
library(dplyr)
library(ggplot2)
library(splitstackshape)
library(stringr)
library(tm)
library(wordcloud)
library(plotly)
library(grid) 
library(tidytext)
library(tidyverse)

# using twitteR package

api_key <- 	"OXp8qCTYZalr5J8JTUpsxmbCG"
api_secret <- "3nGDh4iuIewm2wcXihb9HP9MBvMVOcCQwP3tX1lYYFB8hJNyJl"
access_token <- "4926336342-C1OLbDnPkgsh7EVbfGkjI2mxzFrqpOKdCq6BvY7"
access_token_secret <- "p4Pu5XpgvtCBn8acsqEfGvyaL8IYBfFHsA3odiKvsSR1O"
  
setup_twitter_oauth(api_key, api_secret, access_token, access_token_secret)

```

# getting data from twitter

```{r}
net<-searchTwitter('net a porter',since='2016-12-01', until='2017-12-06', n = 2000,lang="en")

far<-searchTwitter('Farfetch',since='2016-12-01', until='2017-12-06', n = 2000,lang="en")


# Transform tweets list into a data frame
net_raw<-twListToDF(net)
far_raw<-twListToDF(far)

#clean data

net_raw$text<-iconv(net_raw$text, from = "latin1", to = "ASCII", sub="")
net_raw$text<-gsub('http\\S+\\s*', '', net_raw$text)
far_raw$text<-iconv(far_raw$text, from = "latin1", to = "ASCII", sub="")
far_raw$text<-gsub('http\\S+\\s*', '', far_raw$text)
write.csv(net_raw,"net_raw.csv")
write.csv(far_raw,"far_raw.csv")

```

# word cloud

```{r,warning=FALSE}
#word cloud for net a porter
net_raw<-read.csv("net_raw.csv")
wordCorpus<-Corpus(VectorSource(str_replace_all(net_raw$text, "@", "")))
wordCorpus<-tm_map(wordCorpus, content_transformer(tolower))
wordCorpus<-tm_map(wordCorpus, removePunctuation)
wordCorpus<-tm_map(wordCorpus, content_transformer(tolower))
wordCorpus<-tm_map(wordCorpus, removeWords, stopwords("english"))
wordCorpus<-tm_map(wordCorpus, removeWords, c("net a porter","netaporter"))
wordCorpus<-tm_map(wordCorpus, stripWhitespace)
wordCorpus<-tm_map(wordCorpus, removeNumbers)
toSpace<-content_transformer(function (x , pattern ) gsub(pattern, " ", x))
wordCorpus<-tm_map(wordCorpus, toSpace, "/")
wordCorpus<-tm_map(wordCorpus, toSpace, "@")
wordCorpus<-tm_map(wordCorpus, toSpace, "\\|")
netw<-TermDocumentMatrix(wordCorpus)
netw<- as.matrix(netw)
netw<- sort(rowSums(netw),decreasing=TRUE)
netw<- data.frame(word = names(netw),freq=netw)
set.seed(1234)
wordcloud(words = netw$word, freq = netw$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))



#word cloud for Farfetch
far_raw<-read.csv("far_raw.csv")
wordCorpus<-Corpus(VectorSource(str_replace_all(far_raw$text, "@", "")))
wordCorpus<-tm_map(wordCorpus, content_transformer(tolower))
wordCorpus<-tm_map(wordCorpus, removePunctuation)
wordCorpus<-tm_map(wordCorpus, content_transformer(tolower))
wordCorpus<-tm_map(wordCorpus, removeWords, stopwords("english"))
wordCorpus<-tm_map(wordCorpus, removeWords, c("Farfetch","farfetch","farfetchd"))
wordCorpus<-tm_map(wordCorpus, stripWhitespace)
wordCorpus<-tm_map(wordCorpus, removeNumbers)
toSpace<-content_transformer(function (x , pattern ) gsub(pattern, " ", x))
wordCorpus<-tm_map(wordCorpus, toSpace, "/")
wordCorpus<-tm_map(wordCorpus, toSpace, "@")
wordCorpus<- tm_map(wordCorpus, toSpace, "\\|")
farw<-TermDocumentMatrix(wordCorpus)
farw<- as.matrix(farw)
farw<- sort(rowSums(farw),decreasing=TRUE)
farw<- data.frame(word = names(farw),freq=farw)
set.seed(1234)
wordcloud(words = farw$word, freq = farw$freq, min.freq = 1,
          max.words=200, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))

#save wordcloud data

saveRDS(farw,"farw.rds")

saveRDS(netw,"netw.rds")
```

# Timeline

```{r}
#net a porter timeline

nettl<-userTimeline("NETAPORTER",n=500)
nettl<-twListToDF(nettl)
nettl$text<-iconv(nettl$text, from = "latin1", to = "ASCII", sub="")
nettl$text<-gsub('http\\S+\\s*', '', nettl$text)

nettl<-read.csv("nettl.csv")
nettlpic <- plot_ly(nettl, x = ~created, y = ~favoriteCount, name="Favorite", type = 'scatter', mode = 'lines', line=list(color="pink")) %>% add_trace(y=~retweetCount, name="Retweet", type = 'scatter', mode = 'lines', line=list(color="blue")) %>% add_trace(y=max(nettl$favoriteCount, nettl$retweetCount), type = 'scatter', mode = 'lines', line=list(color="purple"), hoverinfo = "text", text = ~text) %>% layout(
                  title = 'Favorites/Retweets of Spotify Twitter NETAPORTER', xaxis = list(title = 'Date'), 
                  yaxis=list(title='Number of favorites/retweets'))

nettlpic


#Farfetch timeline

fartl<-userTimeline("farfetch",n=500)
fartl<-twListToDF(fartl)
fartl$text<-iconv(fartl$text, from = "latin1", to = "ASCII", sub="")
fartl$text<-gsub('http\\S+\\s*', '', fartl$text)

fattl<-read.csv("fartl.csv")
fartlpic<- plot_ly(fartl, x = ~created, y = ~favoriteCount, name="Favorite", type = 'scatter', mode = 'lines', line=list(color="pink")) %>% add_trace(y=~retweetCount, name="Retweet", type = 'scatter', mode = 'lines', line=list(color="blue")) %>% add_trace(y=max(fartl$favoriteCount, fartl$retweetCount), type = 'scatter', mode = 'lines', line=list(color="purple"), hoverinfo = "text", text = ~text) %>% layout(
                  title = 'Favorites/Retweets of Spotify Twitter Farfetch', xaxis = list(title = 'Date'), 
                  yaxis=list(title='Number of favorites/retweets'))

fartlpic


#save timeline data

write.csv(nettl,"nettl.csv")

write.csv(fartl,"fartl.csv")
```

# sentiment (positive and negative words)

```{r}
#sentiment analysis for net a porter

net_raw<-read.csv("net_raw.csv",stringsAsFactors = FALSE)
sentiments
get_sentiments("afinn")
get_sentiments("bing")
get_sentiments("nrc")
netsenti<-net_raw$text
netsenti<-data_frame(line=1:1245, text=netsenti)
netsenti<-netsenti%>%unnest_tokens(word, text)
netsenti<-netsenti%>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()

netsenti%>%
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(y = "Contribution to sentiment",
       x = NULL) +
  coord_flip()


#sentiment analysis for Farfetch

far_raw<-read.csv("far_raw.csv",stringsAsFactors = FALSE)
farsenti<-far_raw$text
farsenti<-data_frame(line=1:1650, text=farsenti)
farsenti<-farsenti%>%unnest_tokens(word, text)

farsenti<-farsenti%>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()

farsenti%>%
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(y = "Contribution to sentiment",
       x = NULL) +
  coord_flip()

#save sentiment analysis  data

saveRDS(farsenti,"farsenti.rds")

saveRDS(netsenti,"netsenti.rds")
```

# maps

```{r}
load("my_oauth.Rdata")

##map fot net a porter

filterStream("netmap.json", 
             track=c("net a porter"), 
             locations = c(-125, 25, -66,50), 
             timeout=200, oauth=my_oauth)
netmap<-parseTweets("netmap.json", verbose = TRUE)
ck1 <- sum(netmap$lat>0, na.rm = TRUE)
ck2 <- sum(netmap$place_lat>0, na.rm = TRUE)
ck3 <- sum(!is.na(netmap$location))
map.data <- map_data("state")   
netpoints <- data.frame(x = as.numeric(netmap$lon),  
                       y = as.numeric(netmap$lat))
netpoints <- netpoints[netpoints$y > 25, ]  
netpoints<-filter(netpoints,y>19&y<65,x>(-161.7)&x<(-68.01))
ggplot(map.data) + 
  geom_map(aes(map_id = region),  
           map = map.data,  
           fill = "white",             
           color = "grey20", size = 0.25) + 
  expand_limits(x = map.data$long, y = map.data$lat) +            
  theme(axis.line = element_blank(),  
        axis.text = element_blank(),  
        axis.ticks = element_blank(),                     
        axis.title = element_blank(),  
        panel.background = element_blank(),  
        panel.border = element_blank(),                     
        panel.grid.major = element_blank(), 
        plot.background = element_blank(),                     
        plot.margin = unit(0 * c( -1.5, -1.5, -1.5, -1.5), "lines")) +  
        geom_point(data = netpoints,             
        aes(x = x, y = y), size = 1,  
        alpha = 1/5, color = "red")  

#map for Farfetch

filterStream("farmap.json", 
             track=c("Farfetch"), 
             locations = c(-125, 25, -66,50), 
             timeout=200, oauth=my_oauth)
farmap<-parseTweets("farmap.json", verbose = TRUE)
ck1 <- sum(farmap$lat>0, na.rm = TRUE)
ck2 <- sum(farmap$place_lat>0, na.rm = TRUE)
ck3 <- sum(!is.na(farmap$location))
map.data <- map_data("state")   
farpoints <- data.frame(x = as.numeric(farmap$lon),  
                       y = as.numeric(farmap$lat))
farpoints <- farpoints[farpoints$y > 25, ]  
farpoints<-filter(farpoints,y>19&y<65,x>(-161.7)&x<(-68.01))
ggplot(map.data) + 
  geom_map(aes(map_id = region),  
           map = map.data,  
           fill = "white",             
           color = "grey20", size = 0.25) + 
  expand_limits(x = map.data$long, y = map.data$lat) +            
  theme(axis.line = element_blank(),  
        axis.text = element_blank(),  
        axis.ticks = element_blank(),                     
        axis.title = element_blank(),  
        panel.background = element_blank(),  
        panel.border = element_blank(),                     
        panel.grid.major = element_blank(), 
        plot.background = element_blank(),                     
        plot.margin = unit(0 * c( -1.5, -1.5, -1.5, -1.5), "lines")) +  
        geom_point(data = farpoints,             
        aes(x = x, y = y), size = 1,  
        alpha = 1/5, color = "blue")  

#save map file

saveRDS(netpoints, file="netpoints.rds")

saveRDS(farpoints, file="farpoints.rds")
```

